---
title: "JSC370 Final Project"
author: "Ella Hugie"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my Final Project website.

```{r echo=FALSE, message=FALSE, warning=FALSE}
source("process_starbucks_data.R")
```


## Showcasing plots {.tabset .tabset-pills}

### Figure 1

```{r chunk1, echo=FALSE}
sb_locs_state_filtered <- sb_locs_state %>% drop_na(population, n_stores)

scatter_plot <- plot_ly(sb_locs_state_filtered, x = ~population, y = ~n_stores, text = ~state.y, mode = "markers", type = "scatter", marker = list(color = "blue")) %>%
  layout(title = "Relationship Between State Population and Number of Starbucks Locations",
         xaxis = list(title = "Population"),
         yaxis = list(title = "Number of Starbucks Locations"),
         showlegend = FALSE)


```

```{r echo=FALSE}
scatter_plot
```


### Figure 2

```{r chunk2, echo=FALSE}
plotly_plot <- topwords %>%
  plot_ly(x = ~word, y = ~word_frequency, type = 'bar', marker = list(color = 'rgb(158,202,225)', line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
  layout(title = 'Top 10 Words in Starbucks Menu Items',
         xaxis = list(title = 'Word'),
         yaxis = list(title = 'Frequency'))


```

```{r echo=FALSE}
plotly_plot
```

{-}


